version: '3.8'

services:
  client:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./client-app:/app
    environment:
      - NODE_ENV=production
  api:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - rest:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: C:/application/postgres
      o: bind
  rest:
    driver: local
    driver_opts:
      type: none
      device: C:/application/rest
      o: bind